#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain

print_info () {
    local subdomain="$1"
    local domain="$2"
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk -F'[ \t]+' 'NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_info "$2" "$1"
elif [ "$#" -eq 1 ]
then
    print_info "www" "$1"
    print_info "lb-01" "$1"
    print_info "web-01" "$1"
    print_info "web-02" "$1"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

