#!/usr/bin/env bash
# shellcheck disable=SC2086
# display information about subdomains

display_info ()
{
    domain="$1"
    subdomain="$2"
    dns_info=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print}')
    echo "The subdomain $subdomain is a $dns_info"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
        display_info "$1" "$subdomain"
    fi
done
