#!/usr/bin/env bash
# this script cretaes a backup of all DBs and compresses them accordingly

sudo mysqldump -p"$1" --all-databases > backup.sql
DATE=$(date +'%d-%m-%Y')
tar -czvf "${DATE}".tar.gz backup.sql
