#!/usr/bin/env bash
#This script fix nginx configuration file in an Ubuntu container so that nginx listens on port 80.

new="80 default_server"
old="8080 default_server"
sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default

service nginx restart
