#!/usr/bin/env bash
#This script fix nginx configuration file in an Ubuntu container so that nginx listens on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
