#!/usr/bin/env bash
# a lot of extra traps
#!/bin/bash

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit 0' SIGQUIT SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2
done
