#!/usr/bin/env bash
# a lot of extra traps

echo $$ > /var/run/myscript.pid

trap "echo 'I hate the kill command'; exit" SIGTERM
trap "echo 'Y U no love me?!'; exit" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 1
done
