#!/usr/bin/env bash
#fizzbuzz stuf

for i in {1..100}; do
  if [ $((i % 15)) -eq 0 ]; then
    echo "- FizzBuzz"
  elif [ $((i % 3)) -eq 0 ]; then
    echo "- Fizz"
  elif [ $((i % 5)) -eq 0 ]; then
    echo "- Buzz"
  else
    echo "- $i"
  fi
done
This script uses a for loop to iterate from 1 to 100 (for i in {1..100}). For each iteration, the script checks if the number is a multiple of 15 (if [ $((i % 15)) -eq 0 ]


