#!/bin/bash

# Get the IP addresses of all active network interfaces
ips=$(ip addr show | grep -Po 'inet \d+\.\d+\.\d+\.\d+' | awk '{print $2}')

# Loop through each IP address and print it
for ip in $ips; do
  echo $ip
done
